### ISSUE TITLE
Create script for moving processed data

### ISSUE THREAD

**Issue by JoranAngevaare** [XAMS-nikhef/amstrax#31]
Currently this is written to[ this folder](https://github.com/XAMS-nikhef/amstrax/blob/f865d8f35dddc5aa75e4eb15c16539d8dc3f9729/amstrax/autoprocessing/submit_stbc.py#L7)

The advantage is that it's easier to check that we do have successfully processed data

**Comment by dipedeserena** [comment]
So the idea would be to process raw data to the `processing_stage` folder for the quality tests (as it is set now), then move the data to another folder (like `xamsl/data_processed` or `xams/data_processed`) to be used for data analysis. Similar to what we do in XENON?

**Comment by JoranAngevaare** [comment]
done
